### ISSUE TITLE
Doesn't work with Firefox

### ISSUE THREAD

**Issue by binarious** [darookee/u2f-two-factor-bundle#25]
The `u2f-api.js` is throwing:
> setting getter-only property "u2f"

Maybe an integration with https://github.com/grantila/u2f-api would be useful.

**Comment by stephanvierkant** [comment]
I can confirm that it doesn't work properly with Firefox.

I agree a file like `js/u2f-api.js` shouldn't be in this repo in the first place. I already looked where that file came from (@darookee?). I'm not sure what's the best way to integrate a JS. 

I'm using Symfony Encore (Webpack) and Yarn (npm) and since this is a Symfony Bundle we *can* assume other users are using it too. Maybe we should assume users to use it too and add `grantila/u2f-api` as an import in `js/auth.js` . Or should we give the user more freedom to use another way of managing dependencies?

**Comment by stephanvierkant** [comment]
I've created a PR, but I'm not very experienced with JS, so please provide some feedback :).
