### ISSUE TITLE
Type Error in U2FAuthenticator

### ISSUE THREAD

**Issue by binarious** [darookee/u2f-two-factor-bundle#36]
The TwoFactorInterface [defines `getU2FKeys` with the return type of `array`](https://github.com/darookee/u2f-two-factor-bundle/blob/873453e8f8802644c0cea7e461db7fa6cb979eb5/Model/U2F/TwoFactorInterface.php#L20), but the `U2FAuthenticator` calls [`toArray()` on that](https://github.com/darookee/u2f-two-factor-bundle/blob/873453e8f8802644c0cea7e461db7fa6cb979eb5/Security/TwoFactor/Provider/U2F/U2FAuthenticator.php#L41).

This results in the following error:
> Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function toArray() on array

**Comment by stephanvierkant** [comment]
I can fix this in #35. `TwoFactorInterface::getU2FKeys` should return `Collection` instead of `array`

What about replacing `\Symfony\Component\Security\Core\User\UserInterface` by `\R\U2FTwoFactorBundle\Model\U2F\TwoFactorInterface` in `\R\U2FTwoFactorBundle\Security\TwoFactor\Provider\U2F\U2FAuthenticator`?

**Comment by binarious** [comment]
Yes, good idea. Thank you.

**Comment by darookee** [comment]
@stephanvierkant Yes, that should be the `TwoFactorInterface` instead of the `UserInterface`. I see you already did this in #35.
